# Generated by Django 3.0 on 2019-12-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('location_text', models.CharField(max_length=140)),
                ('ticket_price', models.IntegerField()),
                ('copy_text', models.TextField()),
            ],
        ),
    ]
