# Generated by Django 3.0 on 2020-01-02 03:56

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='copy_text',
            new_name='alternate_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='start_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='post',
            name='full_size',
            field=models.ImageField(default='images/grimpizza.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
