# Generated by Django 3.0.2 on 2020-01-16 03:08

import django.core.validators
from django.db import migrations, models
import posts.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200102_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default=posts.models.get_default_slug, max_length=24, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
