# Generated by Django 3.0.2 on 2020-01-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200116_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedImage',
            new_name='UploadedImage',
        ),
    ]
