# Generated by Django 3.0.2 on 2020-01-26 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200120_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
