# Generated by Django 3.0.2 on 2020-02-11 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_uploadedimage_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=34, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.UploadedImage'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
