# Generated by Django 3.0.2 on 2020-02-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200211_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='posts.UploadedImage'),
            preserve_default=False,
        ),
    ]
